[project]
name = "designing-multi-agent-systems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "pip>=25.3",
    "requests>=2.32.5",
]
